globalvar filename_input;
filename_input = "";

mm0_base_buffer = -1; //Import buffer
tmd_edit_buffer = -1; //Export buffer
p_index = 0; //counter to keep track of where an object's primitives start from
offset = 0;
v_list = []; //array[array] holds vert indices to seach for duplicate faces

tmd_base = { //Original data, do not edit
	id : 0,
	mmj : false, //MMJ filetype flag
	
	mm0header : { //MM0 file's actual header is just a table linking start of tmd(1) and start of animations(1-2)
		tsize : 0, // 2 or 3 items, table doesn't include the 32bit zero padding right after size 
		pointer : [],
	},
	
	tmd_id : 0x41,
	tmd_flag : 0, //0b1 object refs offset(0=Addr from beginning of Object 1=beginning of TMD)
	obj_num : 0,
	
	tmd_size : 0,
	objects : [],

	packet_data : [], //packet section for MMJ object placement
	prim : [], //entire primitive section - either "prim3" or "Primitive" struct
	vert : [], //entire vertex section - use "vertex" struct
	norm : [],
	final : [], //animation section - can just dump rest of file into here
	
	duplicates : [] //indices of Primitives that share every vertex
}

tmd_edit = { //The modified values should be saved here
	id : 0,
	//mmj : false, //MMJ filetype flag
	
	mm0header : { //MM0 file's actual header is just a table linking start of tmd(1) and start of animations(1-2)
		tsize : 0, // 2 or 3 items, table doesn't include the 32bit zero padding right after size 
		pointer : [],
	},
	
	tmd_id : 0x41,
	tmd_flag : 0, //0b1 object refs offset(0=Addr from beginning of Object 1=beginning of TMD)
	obj_num : 0,
	
	tmd_size : 0,
	objects : [],

	packet_data : [], //packet section for MMJ object placement
	prim : [], //entire primitive section - either "prim3" or "Primitive" struct
	vert : [], //entire vertex section - use "vertex" struct
	norm : [],
	final : [], //animation section
	
	duplicates : [] //indices of Primitives that share every vertex
}

tmd_draw = {
	objects : [],
	packet_data : [], //packet section for MMJ object placement
	vert : [], //entire vertex section - use "vertex" struct
	norm : [],
}

function Object(_prim_index, _Scale, _PrimNum, _PrimOff, _NormNum, _NormOff, _VertNum, _VertOff) constructor{
		vert_off = _VertOff; // + 0x1c if tmd_base.mm0header.size = 3, +0x10 else
		vert_num = _VertNum;
		normal_off = _NormOff; // + 0x1c if tmd_base.mm0header.size = 3, +0x10 else
		normal_num = _NormNum;
		prim_off = _PrimOff; // + 0x1c if tmd_base.mm0header.size = 3, +0x10 else
		prim_num = _PrimNum;
		scale = _Scale;
		prim_index = _prim_index;
}
function Primitive(_rgb_off = 0, _pad = 0, _t_disable = 0, _c_mode = 0, _t_mode = 0, _page_y = 256, _page_x = 0, _clut_y = 0, _clut_x = 0, _cmd = 0, _p_id = 0) constructor{
	p_id = _p_id; 
	p_index = 0; //index in tmd_base.prim + object offset
	r_steps = []; //tracks rotation steps from edit_write to prevent warping
	r_cx = []; //centerX points of r_steps
	r_cy = []; //centerY points of r_steps
	x_diff = [0, 0, 0, 0];
	y_diff = [0, 0, 0, 0];
	
	cmd = _cmd; //Mode u8// Render command
	//0bxx xx xx x1 = Texture Mode      (0=Blended 1=Raw)                (Textured-Polygon/Rectangle only)
	//0bxx xx xx 1x = Semi Transparency (0=Opaque 1=Semi-Transparent)    (All Render Types)
	//0bxx xx x1 xx = Texture Mapping   (0=Off 1=On)                     (Polygon/Rectangle only)
	
	//0bxx x1 1x xx = Rectangle Size    (0=Var 1=1x1 2=8x8 3=16x16)      (Rectangle only)
	//0bxx xx 1x xx = Num Vertices      (0=Triple 1=Quad)                (Polygon only)
	//0bxx xx 1x xx = Num Lines         (0=Single 1=Poly)                (Line only)
	
	//0bxx x1 xx xx = Shading           (0=Flat 1=Gouroud)               (Polygon/Line only)
	//0bx1 1x xx xx = Primitive Type    (1=Polygon 2=Line 3=Rectangle)
	flag = 0; //Flag u8// Rendering options
	//0bxx x1 = GRD (0=Single-Color-Polygon 1=Gradation-Polygon)
	//0bxx 1x = FCE (0=Single-Faced-Polygon 1=Double-Faced-Polygon)
	//0bx1 xx = LGT (0=Light-Source-Calc:On 1=Light-Source-Calc:Off)
	ilen = 0; //Ilen u8// Length in u32 of packet data section. [(u8 Size of entire packet / 4) - 1] 
	olen = 0; //Olen u8// Word length of the 2D drawing primitives that are generated by intermediate processing (???)
	//Example: 0x 09 06 00 34
	//09 = 3 vertices * 3(one each for x, y, z, so 3)
	//06 = 3 vertices + ceil((3norm + 3vert)/2) + 0rgb(u32)
	//00 = (LGT = 0, FCE = 0, GRD = 0) = 0b000
	//34 = CMD
	
	center_xy = [0, 0];
	z_depth = [0, 0]; // [vert_x, vert_z]
	
	tex_x = [];
	tex_y = [];
	clut_x = _clut_x;
	clut_y = _clut_y;
	
	
	page_x = _page_x;       //0bxxxx xxxx xxxx 1111// page_x + (16 * page_y) = page number or page_x * 64 = page x
	page_y = _page_y;       //0bxxxx xxxx xxx1 xxxx// page_y base = page_y * 256;
	t_mode = _t_mode;       //0bxxxx xxxx x11x xxxx// transparency mode
	c_mode = _c_mode;       //0bxxxx xxx1 1xxx xxxx// bit depth
	t_disable = _t_disable; //0bxxxx 1xxx xxxx xxxx// Texture Disable
	
	//1 - 4 u8 -> [00 Bb Gg Rrh] same deal as GPU command + color (u32), except cmd bytes are 00
	colors = []; //Vertex_Color(_blue,_green,_red)
	rgb_off = _rgb_off;
	norm = []; // 3 or 4 x u16
	vert = []; //Vertex(_pad,_vz,_vy,_vz)
	vert_final = []; //Vertex Index + offset from Object header
	norm_final = []; //Normal Index + offset from Object header
	dupe_v = []; //indices of faces that share every single vertex with this primitive
	ax = 0; // vertx average for depth sorting
	az = 0; // vertz average for depth sorting
}
function Vertex(_pad, _vz, _vy, _vx) constructor{
	vx = _vx;
	vy = _vy;
	vz = _vz;
	pad = _pad;
}
function Normal(_pad = 0, _nz, _ny, _nx) constructor{
	nx = _nx;
	ny = _ny;
	nz = _nz;
	pad = _pad;
}
function Vertex_Color(_pad, _blue, _green, _red) constructor{
	r = _red; //u8
	g = _green; //u8
	b = _blue; //u8
	pad = _pad; //u8
}
function packet_TrRo( _sz = 1, _sy = 1, _sx = 1, _rz = 0, _ry = 0, _rx = 0, _tz = 0, _ty = 0, _tx = 0) constructor{
	tx = _tx; //s16
	ty = _ty; //s16
	tz = _tz; //s16
	rx = _rx; //s16 4096 = 360/0 degrees
	ry = _ry; //s16
	rz = _rz; //s16
	sx = _sx; //s16
	sy = _sy; //s16
	sz = _sz; //s16
}
filename_input = get_open_filename_ext("MRDX MM_ Files|*.mmj;*.mmx", "", "","Open MRDX MMJ/MMX File");

if (filename_input != "") {
	file_destination = filename_input;
	base_tag = string_copy(file_destination, string_length(file_destination) - 4, 5);
	new_tag = string_delete(base_tag, 0, 1);
    mm0_base_buffer = buffer_load(filename_input);
    buffer_seek(mm0_base_buffer, buffer_seek_start, 0);
	filename_array = string_split(filename_input, "\\");
	ui_name_mm0 = filename_array[array_length(filename_array) - 1];
	fname_mm0 = string_trim(ui_name_mm0, [".mmj", ".mmx"]);
}
else{
	tmd_base = -1;
	tmd_edit = -1;
	instance_destroy();
	exit;
}
 

 
 while (filename_input != "" && buffer_tell(mm0_base_buffer) + 16 < buffer_get_size(mm0_base_buffer)) {
	 
	 
	tmd_base.mm0header.tsize = buffer_read(mm0_base_buffer, buffer_u32);
	array_push(tmd_base.mm0header.pointer,buffer_read(mm0_base_buffer, buffer_u32));
	array_push(tmd_base.mm0header.pointer,buffer_read(mm0_base_buffer, buffer_u32));
	array_push(tmd_base.mm0header.pointer,buffer_read(mm0_base_buffer, buffer_u32));
	
	if tmd_base.mm0header.tsize == 3 {
		array_push(tmd_base.mm0header.pointer,buffer_read(mm0_base_buffer,buffer_u32));
	}
	else {
		array_push(tmd_base.mm0header.pointer, -1);
	}


	
	tmd_base.tim_id = buffer_read(mm0_base_buffer,buffer_u32);
	tmd_base.version = buffer_read(mm0_base_buffer,buffer_u32);
	tmd_base.obj_num = buffer_read(mm0_base_buffer,buffer_u32);
	
// OBJECTS
	tmd_base.obj_off = buffer_tell(mm0_base_buffer); //base address for each object's offset
	
	for (var i = 0; i < tmd_base.obj_num; i++) {
		obj = new Object(
			0,
			buffer_read(mm0_base_buffer,buffer_u32),
			buffer_read(mm0_base_buffer,buffer_u32),
			buffer_read(mm0_base_buffer,buffer_u32),
			buffer_read(mm0_base_buffer,buffer_u32),
			buffer_read(mm0_base_buffer,buffer_u32),
			buffer_read(mm0_base_buffer,buffer_u32),
			buffer_read(mm0_base_buffer,buffer_u32)
		)
		array_push(tmd_base.objects, obj);
		p_index += tmd_base.objects[i].prim_num;
		tmd_base.objects[i].prim_index = p_index;
	}


	primbase = 0;
	for (var j = 0; j < tmd_base.obj_num; j++) {
		primbase = tmd_base.obj_off + tmd_base.objects[j].prim_off;
		tmd_base.prim_base = primbase;
		
		
		buffer_seek(mm0_base_buffer, buffer_seek_start, primbase);
		
		primbase = tmd_base.objects[j].prim_index - tmd_base.objects[j].prim_num;
		
		tmd_base.prim_offset = 0;
		
		for (var i = 0; i < tmd_base.objects[j].prim_num; i++) {
			primitive = new Primitive();
			array_push(v_list, []);
			v_ind = [];
			
			buffer_seek(mm0_base_buffer, buffer_seek_relative, tmd_base.prim_offset);
			
			//var CMD = buffer_peek(mm0_base_buffer, primbase + 3, buffer_u8);
			primitive.olen = buffer_read(mm0_base_buffer, buffer_u8);
			primitive.ilen = buffer_read(mm0_base_buffer, buffer_u8);
			primitive.flag = buffer_read(mm0_base_buffer, buffer_u8);
			var CMD = buffer_read(mm0_base_buffer, buffer_u8);
			n_index = (tmd_base.objects[j].normal_off - tmd_base.objects[0].normal_off) / 8;
			v_index = (tmd_base.objects[j].vert_off - tmd_base.objects[0].vert_off) / 8;
			
			primitive.p_id = i;
			primitive.p_index = i + primbase;
			primitive.cmd = CMD;
			//array_push(primitive.colors, vert_rgb);
			
			
			//==Decoding primitive's GPU command==
			p_type = (CMD >> 5) & 0b11; //Primitive Type 0b1xx is ignored for our purposes
			p_shading = (CMD >> 4) & 0b1; //Polygon/Line only
			p_line_num = (CMD >> 3) & 0b1; //Line only
			p_poly_vert = (CMD >> 3) & 0b1; //Polygon only
			p_rect_size = (CMD >> 3) & 0b11; //Rectangle only
			p_tex_mapping = (CMD >> 2) & 0b1; //Polygon/Rectangle
			p_transparency = (CMD >> 1) & 0b1; //All Render Types
			p_tex_mode = CMD & 0b1; //Textured-Polygon/Rectangle only
			
			if (p_type == 1){ //
				array_push(primitive.tex_x, buffer_read(mm0_base_buffer, buffer_u8));
				array_push(primitive.tex_y, buffer_read(mm0_base_buffer, buffer_u8));
				clut = buffer_read(mm0_base_buffer, buffer_u16);
				primitive.clut_x = clut & 0b111111;
				primitive.clut_y = (clut >> 6) & 0b1_1111_1111;
				primitive.mbyte = (clut >> 15);
				
				array_push(primitive.tex_x, buffer_read(mm0_base_buffer, buffer_u8));
				array_push(primitive.tex_y, buffer_read(mm0_base_buffer, buffer_u8));
				page = buffer_read(mm0_base_buffer, buffer_u16);
				primitive.page_x = page & 0b1111;
				primitive.page_y = (page >> 4) & 0b1;
				primitive.t_mode = (page >> 5) & 0b11;
				primitive.c_mode = (page >> 7) & 0b11;
				primitive.t_disable = (page >> 11) & 0b1;
				switch (primitive.page_x + 16){
					case 28:
					PageModePrim.vram28 = 1;
					if (primitive.c_mode == 0){
						prim_check28_4bit = true;
					}
					else {
						prim_check28_8bit = true;
					}
					break;
					
					case 29:
					PageModePrim.vram29 = 1;
					if (primitive.c_mode == 0){
						prim_check29_4bit = true;
					}
					else {
						prim_check29_8bit = true;
					}
					break;
					
					case 30:
					PageModePrim.vram30 = 1;
					if (primitive.c_mode == 0){
						prim_check30_4bit = true;
					}
					else {
						prim_check30_8bit = true;
					}
					break;
					
					case 31:
					PageModePrim.vram31 = 1;
					if (primitive.c_mode == 0){
						prim_check31_4bit = true;
					}
					else {
						prim_check31_8bit = true;
					}
					break;
				}
				array_push(primitive.tex_x, buffer_read(mm0_base_buffer, buffer_u8));
				array_push(primitive.tex_y, buffer_read(mm0_base_buffer, buffer_u8));
				if (p_tex_mode == 1){ //raw texture blending
					primitive.rgb_off = buffer_read(mm0_base_buffer, buffer_u16);
					d = 0;
					repeat (3 + p_poly_vert){
						vert_rgb = new Vertex_Color(
							buffer_read(mm0_base_buffer, buffer_u8), //padding
							buffer_read(mm0_base_buffer, buffer_u8), //blue
							buffer_read(mm0_base_buffer, buffer_u8), //green
							buffer_read(mm0_base_buffer, buffer_u8) //red
						);
						array_push(primitive.colors, vert_rgb);
					}
					repeat (3){
						vert_read = buffer_read(mm0_base_buffer, buffer_u16);
						array_push(primitive.vert, vert_read);
						array_push(primitive.vert_final, vert_read + v_index);
						d++;
					}
					if (d % 2){
						buffer_read(mm0_base_buffer, buffer_u16); //padding
					}
					
				}
				else{
					buffer_read(mm0_base_buffer, buffer_u16); //padding
					if (p_poly_vert == 1){
						array_push(primitive.tex_x, buffer_read(mm0_base_buffer, buffer_u8));
						array_push(primitive.tex_y, buffer_read(mm0_base_buffer, buffer_u8));
						buffer_read(mm0_base_buffer, buffer_u16); //padding
					}
					repeat (3 + p_poly_vert){
						norm_read = buffer_read(mm0_base_buffer, buffer_u16);
						array_push(primitive.norm, norm_read);
						array_push(primitive.norm_final, norm_read + n_index);
						
						vert_read = buffer_read(mm0_base_buffer, buffer_u16);
						array_push(primitive.vert, vert_read);
						array_push(primitive.vert_final, vert_read + v_index);
					}
				}
			}
			x_total = 0;
			y_total = 0;
			for (var b = 0; b < array_length(primitive.tex_x); b++){
				x_total += primitive.tex_x[b];
				y_total += primitive.tex_y[b];
			}
			primitive.center_xy = [round((x_total / array_length(primitive.tex_x))), round((y_total / array_length(primitive.tex_y)))];

			array_push(tmd_base.prim, primitive);
		}
	}
	dupe_count = 0;
	for (var a = 0; a < array_length(tmd_base.prim); a++){
		a_list = tmd_base.prim[a].vert;
		for (var b = a + 1; b < array_length(tmd_base.prim); b++){
			b_list = tmd_base.prim[b].vert;
			found = true;
			for (var c = 0; c < array_length(b_list); c++){
				if (array_contains(a_list, b_list[c])){
					pass = 1;
				}
				else {
					found = false;
					break;
				}
			}
			if (found){
				dupe_count++;
				show_debug_message("[Testing]:# of Duplicates Found:{0}", dupe_count);
				show_debug_message("[Testing]:Duplicate Prim Index:a:{0}", a);
				show_debug_message("[Testing]:Duplicate Prim Index:b:{0}", b);
				array_push(tmd_base.duplicates, [tmd_base.prim[a].p_index, tmd_base.prim[b].p_index]);
			}
		}
		
	}
	//buffer_seek(mm0_base_buffer, buffer_seek_start, primbase + 1);
	vert_total = (tmd_base.objects[0].normal_off - tmd_base.objects[0].vert_off) / 8;
	last_object = array_length(tmd_base.objects) - 1;
	norm_total = ((tmd_base.objects[0].scale - 12) - tmd_base.objects[0].normal_off) / 8;
	v_list = [];
	for(var a = 0; a < (vert_total * 8); a += 8){
		vx = buffer_read(mm0_base_buffer, buffer_s16);
		vy =  buffer_read(mm0_base_buffer, buffer_s16);
		vz = buffer_read(mm0_base_buffer, buffer_s16);
		pad = buffer_read(mm0_base_buffer, buffer_s16);
		vertex = new Vertex(pad, vz, vy, vx);
		array_push(tmd_base.vert, vertex);
	}
	for(var a = 0; a < (norm_total * 8); a += 8){

		nx = buffer_read(mm0_base_buffer, buffer_u16);
		ny =  buffer_read(mm0_base_buffer, buffer_u16);
		nz = buffer_read(mm0_base_buffer, buffer_u16);
		pad = buffer_read(mm0_base_buffer, buffer_u16);
		
		normal = new Normal(pad, nz, ny, nx);
		array_push(tmd_base.norm, normal);
	}
	tmd_base.mmj = false;
	tmd_base.tmd_size = tmd_base.objects[0].scale;
	check = buffer_peek(mm0_base_buffer, tmd_base.tmd_size + tmd_base.mm0header.pointer[1], buffer_u16);
	animation_pointer = tmd_base.tmd_size + tmd_base.mm0header.pointer[1];
	
	//Animation data collection
	buffer_seek(mm0_base_buffer, 0, animation_pointer);
	if (check == 4){ //check for MMJ position ID
		tmd_base.mmj = true;
		repeat (8){
			array_push(tmd_base.final, buffer_read(mm0_base_buffer, buffer_u32));
		}
		packet_data_in = [];
		packet_data_start = buffer_read(mm0_base_buffer, buffer_u32);
		buffer_read(mm0_base_buffer, buffer_u32);
		packet_data_end = buffer_read(mm0_base_buffer, buffer_u32);
		unkown_section = buffer_read(mm0_base_buffer, buffer_u32);
		packet_num = (packet_data_end - packet_data_start) / 12;
		for (var a = 0; a < packet_num; a++){
			packet_data_in = new packet_TrRo(
				0,0,0,
				buffer_read(mm0_base_buffer, buffer_s16), //tx
				buffer_read(mm0_base_buffer, buffer_s16), //ty
				buffer_read(mm0_base_buffer, buffer_s16), //tz
				buffer_read(mm0_base_buffer, buffer_s16), //rx
				buffer_read(mm0_base_buffer, buffer_s16), //ry
				buffer_read(mm0_base_buffer, buffer_s16) //rz
			)
			array_push(tmd_base.packet_data, packet_data_in);
		}		
	}	
	else{
		packet_data_in = new packet_TrRo(0, 0, 0, 0, 0, 0);
		array_push(tmd_base.packet_data, packet_data_in);
	}
	
	//Collection of unused data 
	while (buffer_tell(mm0_base_buffer) + 16 < buffer_get_size(mm0_base_buffer)){
		array_push(tmd_base.final,buffer_read(mm0_base_buffer, buffer_s8));
	}
}
tmd_draw = variable_clone(tmd_base); 
for (var a = 0; a < array_length(tmd_base.objects); a++){ //Verts with TrRo packets applied are here
	prim_base = tmd_base.objects[a].prim_index - tmd_base.objects[a].prim_num;
	for (var b = 0; b < tmd_base.objects[a].prim_num; b++){
		for (var c = 0; c < array_length(tmd_base.prim[prim_base + b].tex_x); c++){
			v_index = tmd_base.prim[prim_base + b].vert[c] + ((tmd_base.objects[a].vert_off - tmd_base.objects[0].vert_off) / 8);
			if (a < array_length(tmd_draw.packet_data)){
				tmd_draw.vert[v_index].vx = tmd_base.vert[v_index].vx + tmd_draw.packet_data[a].tx;
				tmd_draw.vert[v_index].vy = tmd_base.vert[v_index].vy + tmd_draw.packet_data[a].ty;
				tmd_draw.vert[v_index].vz = tmd_base.vert[v_index].vz + tmd_draw.packet_data[a].tz;
			}
		}
	}
}
tmd_edit = variable_clone(tmd_draw);
tmd_reverse = variable_clone(tmd_draw);
tmd_reverse.prim = array_reverse(tmd_reverse.prim);
