active = 0;
display = "";
image = 0;
timer = 15
toggle = 0;
toggle_set = 0;
hold = 0;
t_color_off0 = $FF222222 //background text color
t_color_off1 = $FF999999; //foreground text color
t_color_on0 = $FF945A42; //background text color
t_color_on1 = $FFDDCFA0; //foreground text color
enable = 1;
text_x = 28;
y_off = 0;
image_index = image;
image_yscale = 1;